from datetime import date

INPUTS = [
    {
        "festival": "Amsterdam Dance Event",
        "hashtags": [
            {
                "name": "amsterdamdanceevent",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "ade",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "ade",
                "suffix_start": 13,
                "suffix_end": 23,
                "include_without_suffix": False,
            },
            {
                "name": "adeamsterdam",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "Pinkpop",
        "hashtags": [
            {
                "name": "pinkpop",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "pinkpopfestival",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "pinkpopfest",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "Lowlands",
        "hashtags": [
            {
                "name": "lowlands",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "lowlandsfestival",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "Mysteryland",
        "hashtags": [
            {
                "name": "mysteryland",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "mysterylandfestival",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "mysterland",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "Awakenings Festival",
        "hashtags": [
            {
                "name": "awakeningsfestival",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "awakeningssummerfestival",
                "suffix_start": None,
                "suffix_end": None,
                "include_without_suffix": True,
            },
            {
                "name": "awakeningsspringfestival",
                "suffix_start": None,
                "suffix_end": None,
                "include_without_suffix": True,
            },
            {
                "name": "awakeningsamsterdam",
                "suffix_start": None,
                "suffix_end": None,
                "include_without_suffix": True,
            },
            {
                "name": "awakeningseindhoven",
                "suffix_start": None,
                "suffix_end": None,
                "include_without_suffix": True,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "Defqon.1",
        "hashtags": [
            {
                "name": "defqon",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "defqon1",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "defqon1netherlands",
                "suffix_start": None,
                "suffix_end": None,
                "include_without_suffix": True,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "Zwarte Cross",
        "hashtags": [
            {
                "name": "zwartecross",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "zwartecrossfestival",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "zcleven",
                "suffix_start": None,
                "suffix_end": None,
                "include_without_suffix": True,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "Down the Rabbit Hole",
        "hashtags": [
            {
                "name": "dtrh",
                "suffix_start": 13,
                "suffix_end": 23,
                "include_without_suffix": False,
            },
            {
                "name": "dtrh",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "dtrhfest",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "Paaspop",
        "hashtags": [
            {
                "name": "paaspop",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "paaspopfestival",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "Best Kept Secret",
        "hashtags": [
            {
                "name": "bestkeptsecretfestival",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "bks",
                "suffix_start": 13,
                "suffix_end": 23,
                "include_without_suffix": False,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "Welcome To The Future",
        "hashtags": [
            {
                "name": "welcometothefuturefestival",
                "suffix_start": 2015,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "welcometothefuturefest",
                "suffix_start": None,
                "suffix_end": None,
                "include_without_suffix": True,
            },
            {
                "name": "wttffestival",
                "suffix_start": None,
                "suffix_end": None,
                "include_without_suffix": True,
            },
            {
                "name": "wttffest",
                "suffix_start": None,
                "suffix_end": None,
                "include_without_suffix": True,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "Solar Weekend",
        "hashtags": [
            {
                "name": "solarweekend",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "solarweekendfestival",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "Lente Kabinet",
        "hashtags": [
            {
                "name": "lentekabinet",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "lentekabinet",
                "suffix_start": 13,
                "suffix_end": 23,
                "include_without_suffix": False,
            },
            {
                "name": "lentekabinetfestival",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "Amsterdam Music Festival",
        "hashtags": [
            {
                "name": "amsterdammusicfestival",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "amffestival",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "amf",
                "suffix_start": 13,
                "suffix_end": 23,
                "include_without_suffix": False,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "DGTL",
        "hashtags": [
            {
                "name": "dgtlfestival",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "dgtl",
                "suffix_start": 13,
                "suffix_end": 23,
                "include_without_suffix": False,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "Mystic Garden",
        "hashtags": [
            {
                "name": "mysticgarden",
                "suffix_start": 2017,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "mysticgardenfestival",
                "suffix_start": 2017,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "Decibel Outdoor",
        "hashtags": [
            {
                "name": "decibeloutdoor",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "decibeloutdoorfestival",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "Appelpop",
        "hashtags": [
            {
                "name": "appelpop",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "appelpopfestival",
                "suffix_start": None,
                "suffix_end": None,
                "include_without_suffix": True,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "Concert at SEA",
        "hashtags": [
            {
                "name": "concertatsea",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            }
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "North Sea Jazz",
        "hashtags": [
            {
                "name": "northseajazz",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "northseajazzfestival",
                "suffix_start": 2013,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "Woohah",
        "hashtags": [
            {
                "name": "woohahfestival",
                "suffix_start": 2014,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "woohah",
                "suffix_start": 2014,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "Pal Mundo",
        "hashtags": [
            {
                "name": "palmundo",
                "suffix_start": 2014,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "palmundofestival",
                "suffix_start": 2014,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
    {
        "festival": "Into the Woods",
        "hashtags": [
            {
                "name": "intothewoodsfestival",
                "suffix_start": 2014,
                "suffix_end": 2023,
                "include_without_suffix": True,
            },
            {
                "name": "itwfestival",
                "suffix_start": None,
                "suffix_end": None,
                "include_without_suffix": True,
            },
        ],
        "start_date": date(2013, 1, 1),
        "end_date": None,
    },
]

SUBSTANCES = {
    "Stimulants": {
        "Amfetamine": [
            "Speed",
            "Pep",
            "Snelle",
            "Snufjes",
            "Wittebommen",
            "Uppers",
            "Amphetamine",
            "Amf",
            "Sossa",
        ],
        "Methamfetamine": [
            "Yaba",
            "Kristal",
            "Crystalmeth",
            "Ice",
            "Methamphetamine",
            "Meth",
            "Tina",
        ],
        "Cocaïne": [
            "Coke",
            "Snuif",
            "Wittepoeder",
            "Snek",
            "Sneeuw",
            "Wittedame",
            "Charlie",
            "Sos",
            "Whitelighting",
        ],
        "Mephedrone": ["Meow", "Meph", "Miauw", "4MMC", "Mefedron", "Mcat", "Meowmeow"],
        "Poppers": ["Lockerroom", "Aromas", "Pufjes", "Rush", "Aroma"],
        "4CEC": ["Clephedrone"],
        "3MMC": ["Metaphedrone", "3M", "3Mtje", "Poes"],
        "4FMA": ["4Fluormethamphetamine"],
        "3FA": ["3Fluoroamphetamine"],
        "Dexamfetamine": ["Dexxies", "Dex"],
    },
    "Hallucinogens": {
        "LSD": [
            "Trip",
            "Lucy",
            "Zuur",
            "1pLSD",
            "1BLSD",
            "Candyflip",
            "Candyflippen",
            "1plsd",
            "Jediflip",
        ],
        "Paddos": [
            "Shrooms",
            "Truffels",
            "MagicMushrooms",
            "Paddo",
            "MagicMushroom",
            "Hippieflip",
        ],
        "Ayahuasca": ["Heilige drank", "Yage"],
        "2CI": ["TripI", "2CIodine", "Smiles"],
        "DMT": ["BusinessmansTrip", "Spiritueelpoeder"],
        "25INBOMe": ["Smiles", "25I", "N-Bomb"],
        "2CB": ["Erox", "Trip2", "2CBro", "Nexus", "2cbfly", "Nexusflip"],
        "DOX": ["DOM", "DOC", "DOB"],
    },
    "Depressants": {
        "Ketamine": [
            "SpecialK",
            "Keta",
            "K",
            "Kvee",
            "Ket",
            "VitamineK",
            "Kittyflip",
            "Kittyflipping",
        ],
        "Benzodiazepines": [
            "Pammetjes",
            "Valis",
            "Downers",
            "Benzos",
            "Vali",
            "Benzo",
            "Snowseal",
        ],
        "Kratom": ["Ketum", "Thang", "Kratombladeren", "Biak"],
        "GHB": [
            "Liquid X",
            "G",
            "GrievousBodilyHarm",
            "VloeibareXTC",
            "Buisje",
            "TanteG",
            "buisje",
            "tanteG",
        ],
        "Temazepam": ["Temas", "Pammetjes", "Goedslapenpil", "Pam", "Tema"],
        "Cannabis": [
            "Wiet",
            "Hasj",
            "Joint",
            "Weed",
            "Blunt",
            "Pot",
            "MaryJane",
            "ganja",
            "Blowen",
        ],
        "Alcohol": ["Pils", "Zuipen", "Drank", "Bier", "Gerstenat", "Hopwater"],
        "Lachgas": ["N2O", "Ballonnetje", "Nossies", "Lachies"],
    },
    "Other": {
        "XTC": [
            "E",
            "X",
            "XTCpil",
            "Snoepje",
            "Molly",
            "Energiebooster",
            "Ectasy",
            "pirkie",
        ],
        "Tramadol": ["Trammelol", "Trammies", "Trawant", "Trammelant"],
        "4FA": ["4FMP", "4F", "XTClight", "4Fluor", "4F"],
        "Kanna": ["Kougoed", "Channa"],
        "MDA": ["LoveDrug", "XTCPlus", "Adam", "Sass"],
        "3MMC": ["3M", "3Mtje", "Poes"],
        "Spice": ["Fakewiet"],
        "6APB": ["BenzoFury"],
        "Phenibut": ["Fenibut", "HCL"],
        "pregabalin": ["Pregabaline", "Lyrica"],
        "Methoxetamine": ["MXE"],
    },
    "Drugs": {
        "Pillen": ["Pilletjes"],
        "Smoken": ["Spacen", "High", "Stoned", "Trippen"],
    },
}
